#!/usr/bin/env python3
"""Policy catalog scaffolder — generate stub L4 files for a system.

Usage:
    python -m tools.policy_catalog.scaffolder <system-name> [--tier T1|T2|T3]

Creates `~/.hermes/policies/<system>/{governance,runtime,integration,usage}.l4`
with required headers + minimum required RULES filled out as TODO stubs.

Idempotent: refuses to overwrite existing files unless --force.
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

POLICIES_DIR = Path.home() / ".hermes" / "policies"

AXES = ("governance", "runtime", "integration", "usage")

# (axis, [required-rule-names])
REQUIRED_RULES = {
    "governance": [
        "{system}-config-change",
        "{system}-restart-authority",
        "{system}-policy-update",
        "{system}-emergency-override",
    ],
    "runtime": [
        "{system}-vein-emit-sla",
        "{system}-loop-lag-bound",
        "{system}-error-rate-bound",
        "{system}-deps-required",
    ],
    "integration": [
        "{system}-publish-allow",
        "{system}-subscribe-allow",
        "{system}-message-shape",
        "{system}-evidence-required",
    ],
    "usage": [
        "{system}-rate-limit",
        "{system}-quota-daily",
        "{system}-cost-ceiling",
        "{system}-allowed-callers",
    ],
}


def header(system: str, axis: str, tier: str, author: str) -> str:
    return f"""\
-- system: {system}
-- axis: {axis}
-- tier: {tier}
-- author: {author}
-- ratified: PENDING
-- council_signoffs: []
-- supersedes: NONE
-- version: 0.1.0

-- ============================================================
-- TODO: author by {author} — see docs/policy-catalog/SCHEMA.md
-- Generated by scaffolder at {datetime.now(timezone.utc).isoformat(timespec='seconds')}
-- ============================================================

"""


def stub_rule(name: str, axis: str) -> str:
    body = {
        "governance": "GIVEN actor : Agent\nDECIDE actor MAY perform action\nWHEN TODO",
        "runtime": "GIVEN window : TimeWindow\nMUST TODO\nDESPITE NOTHING",
        "integration": "GIVEN msg : Message\nDECIDE system MAY publish msg\nWHEN msg's subject MATCHES \"TODO\"",
        "usage": "GIVEN window : Window\nMUST TODO\nWHERE window's duration IS 60 seconds",
    }[axis]
    return f"§ {name}\n{body}\n\n"


def author_file(system: str, axis: str, tier: str, author: str) -> str:
    out = header(system, axis, tier, author)
    for tmpl in REQUIRED_RULES[axis]:
        out += stub_rule(tmpl.format(system=system), axis)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("system")
    ap.add_argument("--tier", default="T2", choices=("T1", "T2", "T3"))
    ap.add_argument("--author", default=os.environ.get("USER", "unknown"))
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    sys_dir = POLICIES_DIR / args.system
    sys_dir.mkdir(parents=True, exist_ok=True)

    written = []
    skipped = []
    for axis in AXES:
        out_path = sys_dir / f"{axis}.l4"
        if out_path.exists() and not args.force:
            skipped.append(out_path)
            continue
        out_path.write_text(author_file(args.system, axis, args.tier, args.author))
        written.append(out_path)

    print(f"system: {args.system}")
    print(f"tier:   {args.tier}")
    print(f"author: {args.author}")
    print(f"written: {len(written)}")
    for p in written:
        print(f"  + {p}")
    if skipped:
        print(f"skipped (exists): {len(skipped)}  (use --force to overwrite)")
        for p in skipped:
            print(f"  ~ {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
