"""Rego emitter — walks jl4-service OpenAPI schema, produces Rego module.

The OpenAPI spec returned by jl4-service `/deployments/{id}/openapi.json` is
the closest available reflection of the typechecked L4 AST surface. Each
@export'd L4 function appears as a path with a request/response schema.

For governance policies the convention is:
  * one boolean-returning @export named like ``allow``, ``permit``,
    ``is_eligible``, etc.  → emitted as Rego ``allow if { ... }``
  * named obligation predicates (e.g. ``MUST_<x>``) → emitted as Rego
    deny rules (``deny[msg] { not <x> }``)

This v0.1 emitter handles only the boolean-allow path. Obligation/deny
emission is tracked by a separate KR.
"""
from __future__ import annotations

from typing import Optional


HEADER_TEMPLATE = """\
# Generated by tools/l4_agt_compiler/rego_emitter.py
# DO NOT EDIT BY HAND — regenerate from L4 source.
# system: {system}
# axis:   {axis}
package governance.{system_pkg}.{axis_pkg}

import future.keywords.if
import future.keywords.in

default allow := false
"""


def _pkg_safe(name: str) -> str:
    """Rego package segments must be alphanumeric+underscore. Strip dashes."""
    return name.replace("-", "_").replace(".", "_")


def emit_rego(
    openapi_schema: Optional[dict],
    *,
    system: str,
    axis: str,
) -> str:
    """Walk the schema and produce a Rego module string.

    The ``openapi_schema`` is the JSON dict returned by jl4-service's per-
    deployment ``/openapi.json``. We look for `paths` whose POST request
    targets an evaluation endpoint and infer one ``allow`` rule per export.

    For the v0.1 corpus baseline we generate a minimal valid Rego module
    even when the schema is empty — this lets the test suite confirm the
    emitter contract before the full AST walker lands.
    """
    if not system:
        raise ValueError("system is required")
    if not axis:
        raise ValueError("axis is required")

    sys_pkg = _pkg_safe(system)
    axis_pkg = _pkg_safe(axis)
    parts: list[str] = [
        HEADER_TEMPLATE.format(
            system=system,
            axis=axis,
            system_pkg=sys_pkg,
            axis_pkg=axis_pkg,
        )
    ]

    function_names = _extract_export_function_names(openapi_schema)

    if not function_names:
        # No @exports present (or empty schema). Emit a deterministic
        # default-deny module so downstream tooling has something parseable.
        parts.append(
            "# No @export'd L4 decisions found in this axis.\n"
            "# Default-deny remains in effect.\n"
        )
        return "\n".join(parts)

    parts.append("# ---------------------------------------------------------")
    parts.append("# Per-decision allow rules (one per @export'd L4 function)")
    parts.append("# ---------------------------------------------------------\n")

    for fn in function_names:
        rule_name = _pkg_safe(fn)
        parts.append(f"# from L4 @export {fn}")
        parts.append(f"allow if {{")
        parts.append(f"    input.{rule_name} == true")
        parts.append(f"}}\n")

    return "\n".join(parts)


def _extract_export_function_names(schema: Optional[dict]) -> list[str]:
    """Pull function names out of the OpenAPI paths.

    jl4-service exposes each @export as ``/deployments/{id}/functions/{name}/evaluation``.
    Accept ONLY paths whose tail-segment after ``/functions/`` is exactly
    ``<name>/evaluation`` — i.e. no parameterized segments, no batch suffix.
    """
    if not isinstance(schema, dict):
        return []
    raw_paths = schema.get("paths")
    if not isinstance(raw_paths, dict):
        return []
    out: list[str] = []
    for path in raw_paths.keys():
        if not isinstance(path, str):
            continue
        if "/functions/" not in path:
            continue
        after_fn = path.split("/functions/", 1)[1].rstrip("/")
        # Must be exactly: <name>/evaluation  (two segments, no braces)
        segments = after_fn.split("/")
        if len(segments) != 2:
            continue
        if segments[1] != "evaluation":
            continue
        name = segments[0]
        if not name or "{" in name or "}" in name:
            continue
        out.append(name)
    # de-dupe while preserving order
    seen = set()
    deduped = []
    for n in out:
        if n not in seen:
            seen.add(n)
            deduped.append(n)
    return deduped
