"""Kanban repository routing facade (ADR-012 P1).

Routes kanban write operations between the legacy SQLite backend
(``hermes_kanban.kanban_db``) and the new DuckDB adapter
(``hermes_kanban.duckdb_kanban_adapter``) based on the environment
variable ``HERMES_KANBAN_WRITE_BACKEND``:

* ``sqlite`` (default) — SQLite is sole authority. DuckDB is not touched.
* ``dual``            — SQLite is authority; DuckDB is a fire-and-forget
                         mirror. Any mirror failure is logged; the SQLite
                         return value is what the caller sees.
* ``duckdb``          — DuckDB is sole authority (post-P3 authority flip).
                         SQLite is not touched.

Design goals:
  * Zero behavioural change when ``HERMES_KANBAN_WRITE_BACKEND`` is unset
    or ``sqlite`` — every existing kanban call flows through the SQLite
    path exactly as before.
  * Mirror failures never break the primary path (log-only).
  * AUTOINCREMENT ids generated by SQLite (task_events.id, task_runs.id,
    task_comments.id) are passed through to the DuckDB mirror insert so
    parity comparisons downstream see identical row ids.
  * The facade covers ONLY module-level write ops enumerated in ADR-012
    §Appendix A. Read ops go through the SQLite path (with a separate
    duckdb reader used for parity/observation).

Non-goals:
  * Not a full ORM. This is a thin, deliberate router.
  * Not a live migrator. That's ``scripts/kanban-migrate-board-to-duckdb.py``.
  * No cross-process coordination. Each process opens its own DuckDB
    connection under the RLock the adapter already provides.

See also:
  * ``docs/adr/ADR-012-sqlite-kanban-sunset.md``
  * ``docs/adr/ADR-011-duckdb-okr-storage.md`` (precedent pattern)
"""

from __future__ import annotations

import logging
import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterable, Iterator, Optional

from hermes_kanban import kanban_db
from hermes_kanban import duckdb_kanban_adapter as dka

logger = logging.getLogger(__name__)


# --------------------------------------------------------------------------- #
# Backend selection
# --------------------------------------------------------------------------- #

_BACKEND_ENV = "HERMES_KANBAN_WRITE_BACKEND"
_VALID_BACKENDS = ("sqlite", "dual", "duckdb")


def current_backend() -> str:
    """Resolve the active backend from env. Defaults to ``sqlite``.

    Invalid values fall back to ``sqlite`` with a warning — the facade
    must never harden a typo into a data-loss condition.
    """
    v = (os.environ.get(_BACKEND_ENV, "sqlite") or "sqlite").strip().lower()
    if v not in _VALID_BACKENDS:
        logger.warning(
            "invalid %s=%r; falling back to 'sqlite'",
            _BACKEND_ENV, v,
        )
        return "sqlite"
    return v


def _mirror_enabled() -> bool:
    return current_backend() in ("dual", "duckdb")


def _duckdb_authoritative() -> bool:
    return current_backend() == "duckdb"


# --------------------------------------------------------------------------- #
# Connection pairing
#
# The SQLite kanban_db keeps a per-thread cached connection via
# ``kanban_db.connect``. For the DuckDB mirror we open one adapter
# connection per SQLite path, cached the same way.
# --------------------------------------------------------------------------- #

_DUCKDB_CONNS: dict[str, Any] = {}


def _duckdb_conn_for(sqlite_path: Path):
    resolved = str(Path(sqlite_path).resolve())
    conn = _DUCKDB_CONNS.get(resolved)
    if conn is None:
        try:
            conn = dka.connect(dka.duckdb_kanban_path(Path(sqlite_path)))
            _DUCKDB_CONNS[resolved] = conn
        except Exception:  # pragma: no cover — mirror failure only
            logger.exception(
                "kanban facade: failed to open DuckDB mirror for %s",
                sqlite_path,
            )
            conn = None
    return conn


def _sqlite_path_for(conn: sqlite3.Connection) -> Optional[Path]:
    """Recover the on-disk SQLite path from a live connection.

    Uses ``PRAGMA database_list`` which reliably reports the ``main``
    database file. Returns None for in-memory or unusual connections.
    """
    try:
        rows = conn.execute("PRAGMA database_list").fetchall()
    except Exception:
        return None
    for r in rows:
        name = r[1] if len(r) > 1 else None
        path = r[2] if len(r) > 2 else None
        if name == "main" and path:
            return Path(path)
    return None


@contextmanager
def _mirror_context(
    sqlite_conn: sqlite3.Connection,
) -> Iterator[Optional[Any]]:
    """Yield a DuckDB adapter connection, or None if mirroring is disabled.

    Exceptions raised inside the mirror context are swallowed and logged
    (dual mode); the primary SQLite result path is unaffected.
    """
    if not _mirror_enabled():
        yield None
        return
    sqlite_path = _sqlite_path_for(sqlite_conn)
    if sqlite_path is None:
        yield None
        return
    duck = _duckdb_conn_for(sqlite_path)
    try:
        yield duck
    except Exception:  # pragma: no cover — best-effort mirror
        logger.exception("kanban facade: mirror write failed (non-fatal)")


def _safe_mirror(fn, *args, **kwargs) -> None:
    """Call ``fn`` on the DuckDB adapter, log-and-swallow any failure."""
    if not _mirror_enabled():
        return
    try:
        fn(*args, **kwargs)
    except Exception:  # pragma: no cover — best-effort mirror
        logger.exception(
            "kanban facade: mirror op %s failed (non-fatal)",
            getattr(fn, "__name__", "?"),
        )


# --------------------------------------------------------------------------- #
# Public routed write API
#
# NOTE: Signatures deliberately mirror the SQLite kanban_db module-level
# functions. Callers upgrade by swapping the import from ``kanban_db``
# to ``kanban_repository_facade``; behaviour under
# ``HERMES_KANBAN_WRITE_BACKEND=sqlite`` (the default) is byte-identical.
# --------------------------------------------------------------------------- #


def create_task(
    conn: sqlite3.Connection,
    *,
    title: str,
    body: Optional[str] = None,
    assignee: Optional[str] = None,
    created_by: Optional[str] = None,
    workspace_kind: str = "scratch",
    workspace_path: Optional[str] = None,
    tenant: Optional[str] = None,
    priority: int = 0,
    parents: Iterable[str] = (),
    triage: bool = False,
    idempotency_key: Optional[str] = None,
    max_runtime_seconds: Optional[int] = None,
    skills: Optional[Iterable[str]] = None,
    max_retries: Optional[int] = None,
) -> str:
    parents = tuple(parents)
    skills_tuple = tuple(skills) if skills is not None else None
    tid = kanban_db.create_task(
        conn,
        title=title,
        body=body,
        assignee=assignee,
        created_by=created_by,
        workspace_kind=workspace_kind,
        workspace_path=workspace_path,
        tenant=tenant,
        priority=priority,
        parents=parents,
        triage=triage,
        idempotency_key=idempotency_key,
        max_runtime_seconds=max_runtime_seconds,
        skills=list(skills_tuple) if skills_tuple is not None else None,
        max_retries=max_retries,
    )
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(
                dka.create_task,
                duck,
                title=title,
                body=body,
                assignee=assignee,
                created_by=created_by,
                workspace_kind=workspace_kind,
                workspace_path=workspace_path,
                tenant=tenant,
                priority=priority,
                parents=parents,
                triage=triage,
                idempotency_key=idempotency_key,
                max_runtime_seconds=max_runtime_seconds,
                skills=skills_tuple,
                max_retries=max_retries,
                task_id=tid,  # dual-write id passthrough
            )
    return tid


def assign_task(
    conn: sqlite3.Connection, task_id: str, profile: Optional[str]
) -> bool:
    ok = kanban_db.assign_task(conn, task_id, profile)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.assign_task, duck, task_id, profile)
    return ok


def reassign_task(
    conn: sqlite3.Connection, task_id: str, profile: Optional[str]
) -> bool:
    ok = kanban_db.reassign_task(conn, task_id, profile)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.reassign_task, duck, task_id, profile)
    return ok


def link_tasks(
    conn: sqlite3.Connection, parent_id: str, child_id: str
) -> None:
    kanban_db.link_tasks(conn, parent_id, child_id)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.link_tasks, duck, parent_id, child_id)


def unlink_tasks(
    conn: sqlite3.Connection, parent_id: str, child_id: str
) -> bool:
    ok = kanban_db.unlink_tasks(conn, parent_id, child_id)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.unlink_tasks, duck, parent_id, child_id)
    return ok


def add_comment(
    conn: sqlite3.Connection,
    task_id: str,
    author: str,
    body: str,
) -> int:
    cid = kanban_db.add_comment(conn, task_id, author, body)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(
                dka.add_comment,
                duck,
                task_id,
                author,
                body,
                row_id=cid,  # id passthrough
            )
    return cid


def claim_task(
    conn: sqlite3.Connection,
    task_id: str,
    *,
    lock: Optional[str] = None,
    ttl_seconds: int = 900,
    profile: Optional[str] = None,
    step_key: Optional[str] = None,
    max_runtime_seconds: Optional[int] = None,
) -> Optional[int]:
    run_id = kanban_db.claim_task(
        conn,
        task_id,
        lock=lock,
        ttl_seconds=ttl_seconds,
        profile=profile,
        step_key=step_key,
        max_runtime_seconds=max_runtime_seconds,
    )
    with _mirror_context(conn) as duck:
        if duck is not None and run_id is not None:
            _safe_mirror(
                dka.claim_task,
                duck,
                task_id,
                lock=lock,
                ttl_seconds=ttl_seconds,
                profile=profile,
                step_key=step_key,
                max_runtime_seconds=max_runtime_seconds,
                run_id=run_id,  # id passthrough
            )
    return run_id


def heartbeat_claim(
    conn: sqlite3.Connection,
    task_id: str,
    *,
    lock: str,
    ttl_seconds: int = 900,
    note: Optional[str] = None,
) -> bool:
    ok = kanban_db.heartbeat_claim(
        conn, task_id, lock=lock, ttl_seconds=ttl_seconds, note=note
    )
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(
                dka.heartbeat_claim,
                duck,
                task_id,
                lock=lock,
                ttl_seconds=ttl_seconds,
                note=note,
            )
    return ok


def release_stale_claims(
    conn: sqlite3.Connection, *, now: Optional[int] = None
) -> int:
    n = kanban_db.release_stale_claims(conn, now=now)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.release_stale_claims, duck, now=now)
    return n


def reclaim_task(
    conn: sqlite3.Connection, task_id: str, *, force: bool = False
) -> bool:
    ok = kanban_db.reclaim_task(conn, task_id, force=force)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.reclaim_task, duck, task_id, force=force)
    return ok


def complete_task(
    conn: sqlite3.Connection,
    task_id: str,
    *,
    result: Optional[str] = None,
    summary: Optional[str] = None,
    metadata: Optional[dict] = None,
) -> bool:
    ok = kanban_db.complete_task(
        conn, task_id, result=result, summary=summary, metadata=metadata,
    )
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(
                dka.complete_task,
                duck,
                task_id,
                result=result,
                summary=summary,
                metadata=metadata,
            )
    return ok


def block_task(
    conn: sqlite3.Connection,
    task_id: str,
    *,
    reason: str,
    kind: Optional[str] = None,
) -> bool:
    ok = kanban_db.block_task(conn, task_id, reason=reason, kind=kind)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.block_task, duck, task_id, reason=reason, kind=kind)
    return ok


def unblock_task(conn: sqlite3.Connection, task_id: str) -> bool:
    ok = kanban_db.unblock_task(conn, task_id)
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(dka.unblock_task, duck, task_id)
    return ok


def add_kanban_notify_sub(
    conn: sqlite3.Connection,
    *,
    task_id: str,
    platform: str,
    chat_id: str,
    thread_id: str = "",
    user_id: Optional[str] = None,
) -> bool:
    # kanban_db uses `add_notify_sub` name.
    ok = kanban_db.add_notify_sub(
        conn,
        task_id=task_id,
        platform=platform,
        chat_id=chat_id,
        thread_id=thread_id,
        user_id=user_id,
    )
    with _mirror_context(conn) as duck:
        if duck is not None:
            _safe_mirror(
                dka.add_kanban_notify_sub,
                duck,
                task_id=task_id,
                platform=platform,
                chat_id=chat_id,
                thread_id=thread_id,
                user_id=user_id,
            )
    return ok


# --------------------------------------------------------------------------- #
# Read passthroughs (SQLite authority; adapter has its own reads for parity)
# --------------------------------------------------------------------------- #

def get_task(conn: sqlite3.Connection, task_id: str):
    return kanban_db.get_task(conn, task_id)


def list_tasks(conn: sqlite3.Connection, **kwargs):
    return kanban_db.list_tasks(conn, **kwargs)


def list_events(conn: sqlite3.Connection, task_id: str):
    return kanban_db.list_events(conn, task_id)


def list_comments(conn: sqlite3.Connection, task_id: str):
    return kanban_db.list_comments(conn, task_id)


__all__ = [
    "current_backend",
    "create_task", "assign_task", "reassign_task",
    "link_tasks", "unlink_tasks",
    "add_comment",
    "claim_task", "heartbeat_claim",
    "release_stale_claims", "reclaim_task",
    "complete_task", "block_task", "unblock_task",
    "add_kanban_notify_sub",
    "get_task", "list_tasks", "list_events", "list_comments",
]
